### ISSUE TITLE
numClasses is 0

### ISSUE THREAD

**Issue by ArashBayatDev** [fabuzaid21/yggdrasil#1]
Hi, 
I am trying to run the following code

```
val dt = new YggdrasilClassifier().setFeaturesCol("features").setLabelCol("label").setMaxDepth(10)
val model = dt.fit(dfy)
```

where **dfy** looks like

```
+-----+-----------------+
|label|         features|
+-----+-----------------+
|  1.0|[2.0,2.0,0.0,2.0]|
|  1.0|[1.0,1.0,0.0,0.0]|
|  0.0|[1.0,0.0,2.0,1.0]|
|  1.0|[1.0,1.0,0.0,1.0]|
|  1.0|[1.0,2.0,1.0,0.0]|
|  0.0|[2.0,2.0,1.0,2.0]|
|  0.0|[1.0,2.0,0.0,0.0]|
```

but I receive a runtime error as below

```
Exception in thread "main" java.lang.IllegalArgumentException: GiniAggregatorSingle given label 1.0 but requires label < numClasses (= 0).
at org.apache.spark.ml.tree.GiniAggregatorSingle.update(impurities.scala:122)
at org.apache.spark.ml.tree.GiniAggregatorSingle.update(impurities.scala:115)
at org.apache.spark.ml.tree.ImpurityAggregatorSingle.update(impurities.scala:67)
at org.apache.spark.ml.tree.impl.YggdrasilRegression$.trainImpl(YggdrasilRegression.scala:48)
at org.apache.spark.ml.tree.impl.Yggdrasil$.trainImpl(Yggdrasil.scala:317)
at org.apache.spark.ml.tree.impl.Yggdrasil$.train(Yggdrasil.scala:253)
at org.apache.spark.ml.tree.impl.YggdrasilClassifier.train(Yggdrasil.scala:84)
at org.apache.spark.ml.tree.impl.YggdrasilClassifier.train(Yggdrasil.scala:42)
at org.apache.spark.ml.Predictor.fit(Predictor.scala:90)
at Main$delayedInit$body.apply(Main.scala:59)
```

why **numClasses** is equal to 0 and how can I fix this error?

**Comment by fabuzaid21** [comment]
Thanks for filing the issue! I just pushed a fix that should take care of the problem. Also, make sure that the DataFrame has the appropriate schema—you can use this Scala snippet to do so: https://gist.github.com/fabuzaid21/d17923c49205cc40c5f7dc1446891dfe
